'use strict';
const APP_URL='/app';
const api=(action, options={})=>fetch('/api/auth?action='+action, {headers:{'Content-Type':'application/json'},...options}).then(async r=>{const x=await r.json().catch(()=>({})); if(!r.ok) throw new Error(x.error||'अनुरोध पूरा नहीं हुआ।'); return x;});
function showAuthMsg(form,text,kind='error'){if(!form)return;let b=form.querySelector('.auth-msg');if(!b){b=document.createElement('p');b.className='auth-msg';form.prepend(b)}b.textContent=text;b.dataset.kind=kind}
function value(form,id){return String(form.querySelector('#'+id)?.value||'').trim()}
async function submitAuth(form, action){const email=value(form,action==='signup'?'signup-email':'login-email').toLowerCase(), password=value(form,action==='signup'?'signup-password':'login-password'); if(!email||!email.includes('@')) return showAuthMsg(form,'कृपया सही ईमेल भरें।'); if(password.length<8) return showAuthMsg(form,'पासवर्ड कम से कम 8 अक्षर का रखें।'); if(action==='signup'){const name=value(form,'signup-name'),phone=value(form,'signup-phone').replace(/\D/g,''); if(!name||phone.length!==10)return showAuthMsg(form,'नाम और 10 अंकों का मोबाइल नंबर जरूरी है।'); if(password!==value(form,'signup-confirm-password'))return showAuthMsg(form,'दोनों पासवर्ड एक जैसे नहीं हैं।');}
 try{const out=await api(action,{method:'POST',body:JSON.stringify({name:value(form,'signup-name'),phone:value(form,'signup-phone'),email,password})});showAuthMsg(form,'सफलता! प्रोफ़ाइल पूरी करने के लिए ऐप खुल रहा है…','ok');setTimeout(()=>location.href=APP_URL,400)}catch(e){showAuthMsg(form,e.message)}}
function init(){const signup=document.getElementById('signup-form'),login=document.getElementById('login-form'); signup?.addEventListener('submit',e=>{e.preventDefault();submitAuth(signup,'signup')}); login?.addEventListener('submit',e=>{e.preventDefault();submitAuth(login,'login')}); document.querySelectorAll('.form-group__toggle-password').forEach(b=>b.addEventListener('click',()=>{const i=b.closest('.form-group__input-wrapper').querySelector('input');i.type=i.type==='password'?'text':'password'})); document.querySelectorAll('[id$="-google-btn"]').forEach(b=>b.addEventListener('click',()=>showAuthMsg(b.closest('form'),'Google sign-in अभी configured नहीं है। पहले Google OAuth client connect करना होगा।','info')));}
document.addEventListener('DOMContentLoaded',init);
